# Generated by Django 5.2.6 on 2025-10-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RajApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
