# Generated by Django 5.2.6 on 2025-10-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RajApp', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
