# Generated by Django 5.2.6 on 2025-11-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RajApp', '0003_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('areaCode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.TextField()),
                # ('ConfirmPassword', models.TextField()),
                ('remember', models.BooleanField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
