# Generated by Django 5.2.6 on 2025-11-16 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RajApp', '0004_customer_delete_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='userName',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remember',
            field=models.BooleanField(default=False),
        ),
    ]
