# Generated by Django 5.2.6 on 2026-03-02 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RajApp', '0005_rename_username_customer_username_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(default='', max_length=50)),
                ('time', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default='')),
                ('Service_Address', models.TextField(default='')),
                ('Customer_Instruction', models.TextField(default='')),
                ('TotalCharge', models.CharField(default='0')),
                ('Booking_Status', models.CharField(choices=[('Pending', 'Pending'), ('Confirm', 'Confirm'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('Booking_DateTime', models.CharField(default='', max_length=100)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RajApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BathroomCleaning',
            fields=[
                ('BId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('BathroomType', models.CharField(default='', max_length=30)),
                ('No_Of_Bedroom', models.IntegerField(default=0)),
                ('No_Of_Bathroom', models.IntegerField(default=0)),
                ('Is_Hardwater_Stain', models.CharField(default='', max_length=20)),
                ('BathroomBooking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RajApp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDataBase',
            fields=[
                ('BId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(default='Not Defined', max_length=100)),
                ('time', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default='')),
                ('propertyType', models.CharField(default='', max_length=10)),
                ('No_Of_Bedroom', models.IntegerField(default=0)),
                ('No_Of_Bathroom', models.IntegerField(default=0)),
                ('Is_UV_Sanitization', models.CharField(default='', max_length=50)),
                ('Service_Address', models.TextField(default='')),
                ('TotalCharge', models.CharField(default='0')),
                ('Customer_Name', models.CharField(default='', max_length=50)),
                ('Customer_Email', models.CharField(default='', max_length=50)),
                ('Customer_Phone', models.BigIntegerField(null=True)),
                ('Customer_Instruction', models.TextField(default='')),
                ('Booking_DateTime', models.CharField(default='', max_length=100)),
                ('Booking_Status', models.CharField(choices=[('Pending', 'Pending'), ('Confirm', 'Confirm'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RajApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='GardenCleaning',
            fields=[
                ('BId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('GardenSize', models.CharField(default='', max_length=20)),
                ('No_Of_Washroom', models.IntegerField(default=0)),
                ('Is_Grass_Trimming', models.CharField(default='', max_length=20)),
                ('Is_Tree_Trimming', models.CharField(default='', max_length=20)),
                ('GardenBooking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RajApp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenCleaning',
            fields=[
                ('BId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('KitchenType', models.CharField(default='', max_length=30)),
                ('GreaseLevel', models.CharField(default='', max_length=20)),
                ('Is_Chimney_Cleaning', models.CharField(default='', max_length=10)),
                ('KitchenBooking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RajApp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeCleaning',
            fields=[
                ('BId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('OfficeSize', models.CharField(default='', max_length=20)),
                ('No_Of_Washroom', models.IntegerField(default=0)),
                ('Is_Glass_Parition', models.CharField(default='', max_length=10)),
                ('Is_UV_Sanitization', models.CharField(default='', max_length=20)),
                ('OfficeBooking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RajApp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Post_ConstructionCleaning',
            fields=[
                ('BId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ConstructionType', models.CharField(default='', max_length=20)),
                ('PropertySize', models.CharField(default='', max_length=20)),
                ('Is_Construction_Stain', models.CharField(default='', max_length=20)),
                ('ConstructionBooking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RajApp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentalCleaning',
            fields=[
                ('BId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('propertyType', models.CharField(default='', max_length=10)),
                ('No_Of_Bedroom', models.IntegerField(default=0)),
                ('No_Of_Bathroom', models.IntegerField(default=0)),
                ('Is_UV_Sanitization', models.CharField(default='', max_length=50)),
                ('HomeBooking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RajApp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='SofaCleaning',
            fields=[
                ('BId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('SofaType', models.CharField(default='', max_length=20)),
                ('No_Of_Seat', models.IntegerField(default=0)),
                ('Is_Stain_Cleaning', models.CharField(default='', max_length=20)),
                ('SofaBooking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RajApp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='TreeCleaning',
            fields=[
                ('BId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Tree_Service_Type', models.CharField(default='', max_length=20)),
                ('No_Of_Tree', models.IntegerField(default=0)),
                ('Tree_Max_Height', models.CharField(default='', max_length=20)),
                ('TreeBooking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RajApp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='WindoWCleaning',
            fields=[
                ('BId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('WindowType', models.CharField(default='', max_length=20)),
                ('No_Of_Window', models.IntegerField(default=0)),
                ('Window_Side', models.CharField(default='', max_length=20)),
                ('Window_Height', models.CharField(default='', max_length=20)),
                ('WindowBooking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RajApp.booking')),
            ],
        ),
    ]
