# Generated by Django 5.2.6 on 2026-03-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RajApp', '0006_booking_bathroomcleaning_bookingdatabase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officecleaning',
            old_name='Is_Glass_Parition',
            new_name='Is_Glass_Partition',
        ),
        migrations.RemoveField(
            model_name='gardencleaning',
            name='No_Of_Washroom',
        ),
    ]
