# Generated by Django 5.2.6 on 2026-03-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RajApp', '0007_rename_is_glass_parition_officecleaning_is_glass_partition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bathroomcleaning',
            old_name='No_Of_Bedroom',
            new_name='No_Of_Toilet',
        ),
    ]
