# Generated by Django 5.2.6 on 2026-03-06 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RajApp', '0008_rename_no_of_bedroom_bathroomcleaning_no_of_toilet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanzaCommunity',
            fields=[
                ('CommunityId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CommunityEmail', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('ReviewId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ReviewRating', models.IntegerField(default=0)),
                ('ReviewText', models.TextField(default='')),
                ('ReviewBooking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RajApp.booking')),
                ('Reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RajApp.customer')),
            ],
        ),
    ]
