# Generated by Django 5.2.6 on 2026-03-09 17:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RajApp', '0009_cleanzacommunity_customerfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('ContactId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ContactName', models.CharField(default='', max_length=50)),
                ('ContactEmail', models.EmailField(default='', max_length=100)),
                ('ContactPhone', models.CharField(default='', max_length=20)),
                ('ContactQuery', models.CharField(default='', max_length=100)),
                ('ContactMessage', models.TextField(default='')),
            ],
        ),
    ]
