# Generated by Django 5.2.6 on 2026-03-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RajApp', '0010_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='isEmailVerified',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=10),
        ),
    ]
