# Generated by Django 5.2.6 on 2026-03-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RajApp', '0011_customer_bio_customer_isemailverified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WebTheme', models.CharField(default='Dark', max_length=10)),
                ('WebFontSize', models.CharField(default='Medium', max_length=10)),
                ('IsEmailNotification', models.CharField(default='No', max_length=10)),
                ('IsWebNotification', models.CharField(default='No', max_length=10)),
                ('WebLanguage', models.CharField(default='English', max_length=10)),
                ('WebTimeZone', models.CharField(default='IST', max_length=10)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RajApp.customer')),
            ],
        ),
    ]
