# Generated by Django 5.2.6 on 2026-03-27 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RajApp', '0012_usersetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanZaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500, unique=True)),
                ('thumbnail', models.URLField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField(unique=True)),
                ('dateOfPublish', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('readTime', models.IntegerField(default=0)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RajApp.customer')),
            ],
        ),
    ]
